## introduction.py
import streamlit as st
from PIL import Image
import os

## 1 Introduction.py

import streamlit as st
from PIL import Image

st.set_page_config(page_title="Introduction", page_icon="🧠", layout = "wide")


st.title('Introduction')

st.write("")
st.write("")

col1, col2 = st.columns([1.5, 3])

with col1:
    st.header("Glial cells and Gliomas")

    st.write("")

    intro_items1 = ["Glial cells: support neurons in the brain",
                "Gliomas: glial tumors",
                "Most common type of malignant brain tumors",
                "Classification according to histological criteria into:"
                ]
    st.markdown("\n".join([f"- <span style='font-size: 20px'>{item}</span>" for item in intro_items1]), unsafe_allow_html=True)

with col1:
    cola, colb = st.columns([0.2, 2])
    with colb:
        intro_items12 = [ "Oligodendroglioma",
                    "Oligoastrocytoma",
                    "Astrocytoma",
                    "Glioblastoma"
                        ]
        st.markdown("\n".join([f"- <span style='font-size: 20px'>{item}</span>" for item in intro_items12]), unsafe_allow_html=True)


with col2:
    path = os.path.dirname(__file__)
    image1_path = os.path.join(path,"..", "images","750px-Blausen_0870_TypesofNeuroglia_marked_red.png")
    #print("findme2", image1_path)
    image1 = Image.open(image1_path)
    st.image(image1)


st.write("")
st.write("")
st.write("")
st.write("")
col1, col2 = st.columns([1, 1.5])

with col1:
    image2_path = os.path.join(path,"..", "images","41374_2003_Article_BF3780627_Fig1_HTML.jpg")

    image2 = Image.open(image2_path)
    st.image(image2, caption='Histopathologic Classification of Gliomas', use_column_width=False)

with col2:
    st.header("Oligodendroglioma or Astrocytoma?")




######## OLD TEXT ############
st.write("")
st.write("")

intro_items1 = ["Gliomas are the most common type of malignant brain tumor.",
            "They occur in **glial** cells: the cells that surround and support neurons.",
            "A variety of glial cells are found in the nervous system."]
t.markdown("\n".join([f"- <span style='font-size: 18px'>{item}</span>" for item in intro_items1]), unsafe_allow_html=True)
intro_items2 =[
            "Diffuse gliomas represent 80% of malignant brain tumors.",
            "Adult diffuse gliomas are classified and graded according to histological criteria (oligodendroglioma, oligoastrocytoma, astrocytoma, and glioblastoma; grade II to IV).",
            "Histopathologic classification suffers from high intra- and inter-observer variability, particularly among grade II-III tumors.",
            "Recent molecular characterization studies have benefited from the availability of the datasets generated by The Cancer GenomeAtlas (TCGA)."
    ]
st.markdown("\n".join([f"- <span style='font-size: 18px'>{item}</span>" for item in intro_items2]), unsafe_allow_html=True)
