## introduction.py
import streamlit as st
from PIL import Image
import os

## 1 Introduction.py

import streamlit as st
from PIL import Image


st.set_page_config(page_title="Introduction", page_icon="🧠", layout = "wide")

st.title('Introduction')

col1, col2 = st.columns(2)

with col1:
   st.header("Gliomas")

with col2:
    st.write("""
             Gliomas are the most common type of malignant brain tumor. \n
             They occur in **glial** cells: the cells that surround and support neurons. \n
             A variety of glial cells are found in the nervous system.""")

path = os.path.dirname(__file__)
image1_path = os.path.join(path,"..", "images","750px-Blausen_0870_TypesofNeuroglia.png")
#print(image_path)
image1 = Image.open(image1_path)
st.image(image1)

st.markdown('## The Problem')

st.markdown("""
        - Diffuse gliomas represent 80% of malignant brain tumors.
        - Adult diffuse gliomas are classified and graded according to histological criteria (oligodendroglioma, oligoastrocytoma, astrocytoma, and glioblastoma; grade II to IV).
        - Histopathologic classification suffers from high intra- and inter-observer variability, particularly among grade II-III tumors.
        - Recent molecular characterization studies have benefited from the availability of the datasets generated by The Cancer GenomeAtlas (TCGA).
"""
)



st.header("Oligodendroglioma or Astrocytoma?")

image2_path = os.path.join(path,"..", "images","41374_2003_Article_BF3780627_Fig1_HTML.jpg")

image2 = Image.open(image2_path)
st.image(image2, caption='Histopathologic Classification of Gliomas', use_column_width=False)
